spring:
  application:
    name: albaease

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update    # Hibernate가 스키마를 자동 관리
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql  # 원래대로 복원
      encoding: UTF-8
      separator: ;

  #Email 인증
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis 설정
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    com.example.albaease: debug
    org.springframework.data.redis: DEBUG
    org.springframework.data.redis.core: DEBUG
    org.springframework.data.redis.connection: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 3600000 # 1시간 (milliseconds)

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}
    number: ${COOLSMS_SENDER_NUMBER}

websocket:
  allowed-origins: "*"
  endpoint: /ws
  destination-prefixes: /topic, /queue
