name: Deploy Frontend to EC2
on:
  push:
    branches: [ "deployTest" ]  # 배포시 main으로 변경 필요

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci  # npm install 대신 ci 사용해야함 
        
      - name: Build project
        run: npm run build
        
      - name: List build directory
        run: ls -la dist/
        
      - name: Upload build files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "~/frontend/"
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/frontend
            docker-compose down
            docker system prune -f
            docker-compose up -d --build